import SideNav from "@/components/Custom/SideNav";
import TopNav from "@/components/Custom/TopNav";
import { Mulish } from "next/font/google";
import "./globals.css";
import { Provider } from "./Provider";
import { Toaster } from "@/components/ui/sonner";

const MulishFont = Mulish({
  variables: ["300", "500", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${MulishFont.className} antialiased`}>
        <div className="flex w-screen h-screen">
          <SideNav />

          <div className="w-full h-auto flex flex-col ">
            <TopNav />
            <div className="h-full w-full">
              <Provider>{children}</Provider>
            </div>
          </div>
        </div>
        <Toaster/>
      </body>
    </html>
  );
}
